export const WEAPON_CATEGORIES: Record<string, number[]> = {
  rifles: [7, 8, 10, 13, 16, 39, 60],
  snipers: [9, 11, 38, 40],
  pistols: [1, 2, 3, 4, 30, 31, 32, 36, 61, 63, 64],
  smgs: [17, 19, 23, 24, 26, 33, 34],
  heavys: [14, 25, 27, 28, 29, 35],
};

export const WEAPON_DISPLAY_NAMES: Record<string, string> = {
  weapon_ak47: "AK-47",
  weapon_m4a1: "M4A4",
  weapon_m4a1_silencer: "M4A1-S",
  weapon_awp: "AWP",
  weapon_deagle: "Desert Eagle",
  weapon_usp_silencer: "USP-S",
  weapon_glock: "Glock-18",
  weapon_hkp2000: "P2000",
  weapon_elite: "Dual Berettas",
  weapon_fiveseven: "Five-SeveN",
  weapon_tec9: "Tec-9",
  weapon_cz75a: "CZ75-Auto",
  weapon_revolver: "R8 Revolver",
  weapon_p250: "P250",
  weapon_famas: "FAMAS",
  weapon_galilar: "Galil AR",
  weapon_aug: "AUG",
  weapon_sg556: "SG 553",
  weapon_ssg08: "SSG 08",
  weapon_scar20: "SCAR-20",
  weapon_g3sg1: "G3SG1",
  weapon_mac10: "MAC-10",
  weapon_mp9: "MP9",
  weapon_mp7: "MP7",
  weapon_mp5sd: "MP5-SD",
  weapon_ump45: "UMP-45",
  weapon_p90: "P90",
  weapon_bizon: "PP-Bizon",
  weapon_nova: "Nova",
  weapon_xm1014: "XM1014",
  weapon_mag7: "MAG-7",
  weapon_sawedoff: "Sawed-Off",
  weapon_m249: "M249",
  weapon_negev: "Negev",
  weapon_taser: "Zeus x27",
  weapon_knife: "Knife",
  weapon_knife_bayonet: "Bayonet",
  weapon_knife_butterfly: "Butterfly Knife",
  weapon_knife_falchion: "Falchion Knife",
  weapon_knife_flip: "Flip Knife",
  weapon_knife_gut: "Gut Knife",
  weapon_knife_karambit: "Karambit",
  weapon_knife_m9_bayonet: "M9 Bayonet",
  weapon_knife_push: "Shadow Daggers",
  weapon_knife_stiletto: "Stiletto Knife",
  weapon_knife_talon: "Talon Knife",
  weapon_knife_ursus: "Ursus Knife",
  weapon_knife_navaja: "Navaja Knife",
  weapon_knife_cord: "Cord Knife",
  weapon_knife_css: "Classic Knife",
  weapon_knife_cani: "Survival Knife",
  weapon_knife_outdoor: "Nomad Knife",
  weapon_knife_skeleton: "Skeleton Knife",
  weapon_knife_kukri: "Kukri Knife",
  studded_bloodhound_gloves: "Bloodhound Gloves",
  sporty_gloves: "Sport Gloves",
  slick_gloves: "Driver Gloves",
  leather_handwraps: "Hand Wraps",
  motorcycle_gloves: "Moto Gloves",
  specialist_gloves: "Specialist Gloves",
  studded_brokenfang_gloves: "Broken Fang Gloves",
  studded_hydra_gloves: "Hydra Gloves",
};

export const CATEGORY_LABELS: Record<string, string> = {
  knives: "Knives",
  gloves: "Gloves",
  rifles: "Rifles",
  snipers: "Snipers",
  smgs: "SMGs",
  heavys: "Heavys",
  pistols: "Pistols",
  agents: "Agents",
  music: "Music Kits",
};
